language: go

go:
    - 1.16

sudo: false

install:
    - go get -d -v -u ./...
    - go get github.com/mattn/goveralls

script:
    - GOOS=darwin go build
    - GOOS=windows go build
    - GOOS=linux go build
